# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
user1 = User.create(name: 'Евгений')
user2 = User.create(name: 'Сергей')

category = Category.create(title: 'Java')
  test     = Test.create(title: 'Java - Основы', level: 1, category_id: category.id)
    question = Question.create(text: 'Какие пакеты автоматически импортируются во все Java-программы?', test_id: test.id)
      answer   = Answer.create(text: 'java.util', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'java.lang', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'java.security', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'java.io', correct: false, question_id: question.id)
    question = Question.create(text: 'Какая максимальная длина имени переменной допустима в Java?', test_id: test.id)
      answer   = Answer.create(text: '256', correct: false, question_id: question.id)
      answer   = Answer.create(text: '1024', correct: false, question_id: question.id)
      answer   = Answer.create(text: '8', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'не ограничена', correct: false, question_id: question.id)
    question = Question.create(text: 'Каким образом можно запретить наследование класса?', test_id: test.id)
      answer   = Answer.create(text: 'Добавить модификатор final', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'Не определять конструктор', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'Добавить модификатор private', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'Запретить наследование нельзя', correct: false, question_id: question.id)
    user_test = UserTest.create(user_id: user1.id, test_id: test.id)

category = Category.create(title: 'Python')
  test     = Test.create(title: 'Python - Основы', level: 1, category_id: category.id)
    question = Question.create(text: 'Что напечатает код?\ndef func(n):\n  n = n + 1\nprint(func(0))', test_id: test.id)
      answer   = Answer.create(text: '0', correct: false, question_id: question.id)
      answer   = Answer.create(text: '1', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'func(0)', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'None', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'Ошибка', correct: false, question_id: question.id)
    question = Question.create(text: 'Какой результат даст выражение True + 4?', test_id: test.id)
      answer   = Answer.create(text: 'False', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'True', correct: false, question_id: question.id)
      answer   = Answer.create(text: '5', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'Ошибка', correct: false, question_id: question.id)
    question = Question.create(text: 'Какая из функций вернёт вернёт итерируемый объект?', test_id: test.id)
      answer   = Answer.create(text: 'len()', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'xrange()', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'range()', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'ord()', correct: false, question_id: question.id)
    user_test = UserTest.create(user_id: user1.id, test_id: test.id)
    user_test = UserTest.create(user_id: user2.id, test_id: test.id)

category = Category.create(title: 'CSS')
  test     = Test.create(title: 'CSS - Основы', level: 0, category_id: category.id)
    question = Question.create(text: 'Какую рамку задаёт следующая строка? Border: 2px dotted #0000FF;', test_id: test.id)
      answer   = Answer.create(text: '2px, синюю, пунктирную', correct: false, question_id: question.id)
      answer   = Answer.create(text: '2px, зелёную, пунктирную', correct: false, question_id: question.id)
      answer   = Answer.create(text: '2px, красную, сплошную', correct: false, question_id: question.id)
      answer   = Answer.create(text: '2px, синюю, двойную', correct: false, question_id: question.id)
    question = Question.create(text: 'Какое свойство для создания и управления колонками в многоколоночном тексте ' +
                                     'позволяет изменить расстояние между ними?', test_id: test.id)
      answer   = Answer.create(text: 'margin', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'column-padding', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'column-margin', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'padding', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'column-gap', correct: false, question_id: question.id)
    question = Question.create(text: 'Какие значения может принимать opacity?', test_id: test.id)
      answer   = Answer.create(text: '0-100', correct: false, question_id: question.id)
      answer   = Answer.create(text: '0-50', correct: false, question_id: question.id)
      answer   = Answer.create(text: '0-10', correct: false, question_id: question.id)
      answer   = Answer.create(text: '0-1', correct: false, question_id: question.id)
    user_test = UserTest.create(user_id: user1.id, test_id: test.id)
    user_test = UserTest.create(user_id: user2.id, test_id: test.id)

category = Category.create(title: 'SQL')
  test     = Test.create(title: 'SQL - Основы', level: 2, category_id: category.id)
    question = Question.create(text: 'Какое необязательное ключевое слово пропущено в выражении? \ninsert table_name ' +
                                     '(column1, column2) values ("value1", "value2")', test_id: test.id)
      answer   = Answer.create(text: 'OUT', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'IN', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'NAME', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'TO', correct: false, question_id: question.id)
    question = Question.create(text: 'Какое представление имеет значение ноль для типа DATE?', test_id: test.id)
      answer   = Answer.create(text: '00:00:00', correct: false, question_id: question.id)
      answer   = Answer.create(text: '0000', correct: false, question_id: question.id)
      answer   = Answer.create(text: '00-00-0000', correct: false, question_id: question.id)
      answer   = Answer.create(text: '00-00-00', correct: false, question_id: question.id)
      answer   = Answer.create(text: '0000-00-00', correct: false, question_id: question.id)
    question = Question.create(text: 'Перечислите все способы создания новой базы animals.', test_id: test.id)
      answer   = Answer.create(text: 'CREATE NEW DATABASE animals;', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'CREATE SCHEMA animals;', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'CREATE DATABASE IF NOT EXISTS;', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'CREATE animals AS DATABASE;', correct: false, question_id: question.id)
      answer   = Answer.create(text: 'CREATE DATABASE animals;', correct: false, question_id: question.id)
    user_test = UserTest.create(user_id: user2.id, test_id: test.id)
